### ISSUE TITLE
generate responsive gutter widths

### ISSUE THREAD

**Issue by murtali** [karolis-sh/tailwind-bootstrap-grid#48]
hi -- is there a way to generate responsive gutter widths ie:
```
gridGutterWidth (default - "30px") - { sm: '20px', lg: '40px' } 
containerMaxWidths (default - { sm: '540px', md: '720px', lg: '960px', xl: '1140px' }
```

(so gutters change dynamically between desktop/mobile)

thanks

**Comment by karolis-sh** [comment]
Hello,  currently that's not supported, but seems like a valid feature request.

**Comment by karolis-sh** [comment]
Feature release with `2.2.0 `

**Comment by arthurshlain** [comment]
Hello, at `5.0.1` got `ValidationError: "gridGutterWidth" must be a string`.

```js
const tailwindBootstrapGrid = require('tailwind-bootstrap-grid')({
    containerMaxWidths: {
        'sm': '540px',
        'md': '720px',
        'lg': '960px',
        'xl': '1140px',
        '2xl': '1216px',
    },
    gridGutterWidth: {
        'sm': '1.25rem',
        'md': '2rem'
    }
});
```

**Comment by karolis-sh** [comment]
@arthurshlain yeah it seems I removed that in 4.0.0 release https://github.com/karolis-sh/tailwind-bootstrap-grid/blob/main/CHANGELOG.md#400-2021-05-19
I think it was to align with original bootstrap options https://getbootstrap.com/docs/4.0/layout/grid/#columns-and-gutters

**Comment by spostad7** [comment]
@karolis-sh 
how to have something like this?:
gridGutterWidth (default - "30px") - { sm: '20px', lg: '40px' } 

I want to have different gutters width on mobile and large screens

**Comment by arthurshlain** [comment]
@spostad7 I did something like this:

```css
@layer base {
    .row {
        --bs-gutter-x: 30px !important;
    }
    @media (max-width: 767px){
        .row {
            --bs-gutter-x: 15px !important;
        }
    }
}
```
